apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      imagePullSecrets:
        - name: ecrsecret
      containers:
        - name: frontend
          tty: true
          image: MY_ACCOUNT.dkr.ecr.eu-west-1.amazonaws.com/learning-frontend:v29446ea079d6df7875c08c6641523f8e029caf37
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000